config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :ojibwe_words

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ojibwe_word.rb
class OjibweWord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/ojibwe_words_controller.rb
class OjibweWordsController < ApplicationController
  before_action :set_ojibwe_word, only: [:show, :edit, :update, :destroy]

  # GET /ojibwe_words
  # GET /ojibwe_words.json
  def index
    @ojibwe_words = OjibweWord.all
  end

  # GET /ojibwe_words/1
  # GET /ojibwe_words/1.json
  def show
  end

  # GET /ojibwe_words/new
  def new
    @ojibwe_word = OjibweWord.new
  end

  # GET /ojibwe_words/1/edit
  def edit
  end

  # POST /ojibwe_words
  # POST /ojibwe_words.json
  def create
    @ojibwe_word = OjibweWord.new(ojibwe_word_params)

    respond_to do |format|
      if @ojibwe_word.save
        format.html { redirect_to @ojibwe_word, notice: 'Ojibwe word was successfully created.' }
        format.json { render :show, status: :created, location: @ojibwe_word }
      else
        format.html { render :new }
        format.json { render json: @ojibwe_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ojibwe_words/1
  # PATCH/PUT /ojibwe_words/1.json
  def update
    respond_to do |format|
      if @ojibwe_word.update(ojibwe_word_params)
        format.html { redirect_to @ojibwe_word, notice: 'Ojibwe word was successfully updated.' }
        format.json { render :show, status: :ok, location: @ojibwe_word }
      else
        format.html { render :edit }
        format.json { render json: @ojibwe_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ojibwe_words/1
  # DELETE /ojibwe_words/1.json
  def destroy
    @ojibwe_word.destroy
    respond_to do |format|
      format.html { redirect_to ojibwe_words_url, notice: 'Ojibwe word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ojibwe_word
      @ojibwe_word = OjibweWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ojibwe_word_params
      params.require(:ojibwe_word).permit(:english_word, :ojibwe_translation, :word_type, :catagory, :dictionary, :dialect_locale)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/ojibwe_words_helper.rb
module OjibweWordsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ojibwe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/ojibwe_words/_form.html.erb
<%= form_for @ojibwe_word, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :english_word, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :english_word, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ojibwe_translation, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :ojibwe_translation, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :word_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :word_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :catagory, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :catagory, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dictionary, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :dictionary, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dialect_locale, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :dialect_locale, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ojibwe_words_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ojibwe_words/edit.html.erb
<%- model_class = OjibweWord -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => OjibweWord %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ojibwe_words/index.html.erb
<%- model_class = OjibweWord -%>
<div class="page-header">
  <h1><%=t '.title', :default => OjibweWord %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:english_word) %></th>
      <th><%= model_class.human_attribute_name(:ojibwe_translation) %></th>
      <th><%= model_class.human_attribute_name(:word_type) %></th>
      <th><%= model_class.human_attribute_name(:catagory) %></th>
      <th><%= model_class.human_attribute_name(:dictionary) %></th>
      <th><%= model_class.human_attribute_name(:dialect_locale) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ojibwe_words.each do |ojibwe_word| %>
      <tr>
        <td><%= ojibwe_word.id %></td>
        <td><%= ojibwe_word.english_word %></td>
        <td><%= ojibwe_word.ojibwe_translation %></td>
        <td><%= ojibwe_word.word_type %></td>
        <td><%= ojibwe_word.catagory %></td>
        <td><%= ojibwe_word.dictionary %></td>
        <td><%= ojibwe_word.dialect_locale %></td>
        <td><%=l ojibwe_word.created_at, format: :long %></td>
        <td>
          <%= link_to ojibwe_word_path(ojibwe_word), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to ojibwe_word_path(ojibwe_word), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ojibwe_word_path,
            :class => 'btn btn-primary' %>

app/views/ojibwe_words/new.html.erb
<%- model_class = OjibweWord -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => OjibweWord %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ojibwe_words/show.html.erb
<%- model_class = OjibweWord -%>
<div class="page-header">
  <h1><%=t '.title', :default => OjibweWord %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:english_word) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.english_word %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ojibwe_translation) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.ojibwe_translation %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:word_type) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.word_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:catagory) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.catagory %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dictionary) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.dictionary %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dialect_locale) %></dt>
      <dd><pre class="prettyprint"><%= @ojibwe_word.dialect_locale %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ojibwe_words_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ojibwe_word_path(@ojibwe_word), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ojibwe_word_path(@ojibwe_word),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>